# Generated by Django 5.2.8 on 2025-12-02 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lat', models.FloatField(help_text='Latitude coordinate')),
                ('lon', models.FloatField(help_text='Longitude coordinate')),
                ('secret_word', models.CharField(help_text='Secret keyword to unlock', max_length=100)),
                ('sequence_order', models.IntegerField(help_text='Order in which POI must be visited (1-6)', unique=True)),
                ('icon', models.CharField(default='📍', max_length=10)),
                ('qr_code_url', models.URLField(blank=True, help_text='URL for QR code image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Point of Interest',
                'verbose_name_plural': 'Points of Interest',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_word', models.CharField(help_text='Word submitted by participant', max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.participant')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.poi')),
            ],
            options={
                'verbose_name_plural': 'Progress',
                'ordering': ['found_at'],
                'unique_together': {('participant', 'poi')},
            },
        ),
    ]
